import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Loader2 } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export default function ExportTimetableButton({ type, entityId, scheduleVersionId, label = 'Export PDF' }) {
  const [isLoading, setIsLoading] = useState(false);

  const handleExport = async () => {
    if (!entityId || !scheduleVersionId) return;

    setIsLoading(true);
    try {
      const targetId = type === 'student' ? 'student-viewer-timetable' : 'teacher-viewer-timetable';
      const element = document.getElementById(targetId);
      if (!element) {
        throw new Error('Timetable not found');
      }

      const canvas = await html2canvas(element, {
        scale: 2,
        logging: false,
        useCORS: true,
        backgroundColor: '#ffffff',
        removeContainer: true,
        imageTimeout: 0,
      });

      const imgData = canvas.toDataURL('image/png', 1.0);
      const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const margin = 10;
      const headerHeight = 24;
      const footerHeight = 12;
      const contentTop = margin + headerHeight;
      const contentBottom = margin + footerHeight;
      const maxWidth = pdfWidth - (margin * 2);
      const maxHeight = pdfHeight - contentTop - contentBottom;
      const scale = Math.min(maxWidth / (canvas.width * 0.264583), maxHeight / (canvas.height * 0.264583));
      const scaledWidth = (canvas.width * 0.264583) * scale;
      const scaledHeight = (canvas.height * 0.264583) * scale;
      const x = (pdfWidth - scaledWidth) / 2;
      const y = contentTop + ((maxHeight - scaledHeight) / 2);
      const exportDate = new Date().toLocaleDateString('en-GB');
      const exportTime = new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
      const title = type === 'student' ? 'Student Timetable' : 'Teacher Timetable';

      pdf.setFillColor(15, 23, 42);
      pdf.rect(0, 0, pdfWidth, 18, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(16);
      pdf.text('Schedual', margin, 11);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.text('Generated by schedual-pro.com', margin, 15);

      pdf.setTextColor(15, 23, 42);
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(14);
      pdf.text(title, margin, 28);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.text(`Exported on ${exportDate} at ${exportTime}`, margin, 33);
      pdf.text(`Version ID: ${scheduleVersionId}`, pdfWidth - margin, 33, { align: 'right' });

      pdf.setDrawColor(226, 232, 240);
      pdf.roundedRect(x - 2, y - 2, scaledWidth + 4, scaledHeight + 4, 4, 4);
      pdf.addImage(imgData, 'PNG', x, y, scaledWidth, scaledHeight, undefined, 'FAST');

      pdf.setDrawColor(226, 232, 240);
      pdf.line(margin, pdfHeight - 10, pdfWidth - margin, pdfHeight - 10);
      pdf.setTextColor(100, 116, 139);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8);
      pdf.text('Generated by Schedual Pro for sharing, printing, and timetable review.', margin, pdfHeight - 5);
      pdf.text('schedual-pro.com', pdfWidth - margin, pdfHeight - 5, { align: 'right' });

      pdf.save(`${type}-timetable.pdf`);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Button type="button" variant="outline" size="sm" onClick={handleExport} disabled={isLoading || !entityId || !scheduleVersionId}>
      {isLoading ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Download className="w-4 h-4 mr-2" />}
      {isLoading ? 'Exporting...' : label}
    </Button>
  );
}