import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

function addPdfChrome(pdf, { title, scheduleVersionId }) {
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();
  const margin = 10;
  const exportDate = new Date().toLocaleDateString('en-GB');
  const exportTime = new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

  pdf.setFillColor(15, 23, 42);
  pdf.rect(0, 0, pdfWidth, 18, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(16);
  pdf.text('Schedual', margin, 11);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  pdf.text('Generated by schedual-pro.com', margin, 15);

  pdf.setTextColor(15, 23, 42);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.text(title, margin, 28);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  pdf.text(`Exported on ${exportDate} at ${exportTime}`, margin, 33);
  pdf.text(`Version ID: ${scheduleVersionId}`, pdfWidth - margin, 33, { align: 'right' });

  pdf.setDrawColor(226, 232, 240);
  pdf.line(margin, pdfHeight - 10, pdfWidth - margin, pdfHeight - 10);
  pdf.setTextColor(100, 116, 139);
  pdf.setFontSize(8);
  pdf.text('Generated by Schedual Pro for sharing, printing, and timetable review.', margin, pdfHeight - 5);
  pdf.text('schedual-pro.com', pdfWidth - margin, pdfHeight - 5, { align: 'right' });

  return { pdfWidth, pdfHeight, margin };
}

export async function exportGridPdf({ elementId, type, scheduleVersionId, orientation = 'landscape' }) {
  const element = document.getElementById(elementId);
  if (!element) throw new Error('Timetable not found');

  const canvas = await html2canvas(element, {
    scale: 2,
    logging: false,
    useCORS: true,
    backgroundColor: '#ffffff',
    removeContainer: true,
    imageTimeout: 0,
  });

  const pdf = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
  const { pdfWidth, pdfHeight, margin } = addPdfChrome(pdf, {
    title: type === 'student' ? 'Student Timetable' : 'Teacher Timetable',
    scheduleVersionId,
  });

  const imgData = canvas.toDataURL('image/png', 1.0);
  const headerHeight = 24;
  const footerHeight = 12;
  const contentTop = margin + headerHeight;
  const contentBottom = margin + footerHeight;
  const maxWidth = pdfWidth - (margin * 2);
  const maxHeight = pdfHeight - contentTop - contentBottom;
  const scale = Math.min(maxWidth / (canvas.width * 0.264583), maxHeight / (canvas.height * 0.264583));
  const scaledWidth = (canvas.width * 0.264583) * scale;
  const scaledHeight = (canvas.height * 0.264583) * scale;
  const x = (pdfWidth - scaledWidth) / 2;
  const y = contentTop + ((maxHeight - scaledHeight) / 2);

  pdf.setDrawColor(226, 232, 240);
  pdf.roundedRect(x - 2, y - 2, scaledWidth + 4, scaledHeight + 4, 4, 4);
  pdf.addImage(imgData, 'PNG', x, y, scaledWidth, scaledHeight, undefined, 'FAST');
  pdf.save(`${type}-timetable.pdf`);
}

export function exportListPdf({ type, scheduleVersionId, lessons = [], title }) {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const { pdfWidth, pdfHeight, margin } = addPdfChrome(pdf, { title, scheduleVersionId });

  let y = 42;
  pdf.setTextColor(15, 23, 42);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(10);
  pdf.text('Day', margin, y);
  pdf.text('Time', 45, y);
  pdf.text('Subject', 75, y);
  pdf.text('Teacher / Room', 130, y);
  y += 6;

  pdf.setDrawColor(226, 232, 240);
  pdf.line(margin, y - 2, pdfWidth - margin, y - 2);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);

  lessons.forEach((lesson) => {
    if (y > pdfHeight - 20) {
      pdf.addPage();
      addPdfChrome(pdf, { title, scheduleVersionId });
      y = 42;
    }

    pdf.text(String(lesson.day || '-'), margin, y);
    pdf.text(String(lesson.time || '-'), 45, y);
    pdf.text(String(lesson.subject || '-'), 75, y);
    pdf.text(String(lesson.meta || '-'), 130, y);
    y += 7;
  });

  pdf.save(`${type}-timetable-list.pdf`);
}

export function exportSummaryPdf({ type, scheduleVersionId, title, summaryCards = [], lessons = [] }) {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const { pdfWidth, margin } = addPdfChrome(pdf, { title, scheduleVersionId });

  let y = 42;
  summaryCards.forEach((card, index) => {
    const x = index % 2 === 0 ? margin : pdfWidth / 2 + 2;
    const width = pdfWidth / 2 - margin - 4;
    if (index % 2 === 0 && index > 0) y += 22;

    pdf.setFillColor(248, 250, 252);
    pdf.roundedRect(x, y, width, 16, 3, 3, 'F');
    pdf.setTextColor(100, 116, 139);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.text(card.label, x + 4, y + 6);
    pdf.setTextColor(15, 23, 42);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.text(String(card.value), x + 4, y + 12);
  });

  y += summaryCards.length > 2 ? 28 : 22;
  pdf.setTextColor(15, 23, 42);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  pdf.text('Compact lesson summary', margin, y);
  y += 8;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  lessons.slice(0, 12).forEach((lesson) => {
    pdf.text(`• ${lesson.day || '-'}  ${lesson.time || '-'}  ${lesson.subject || '-'}  ${lesson.meta || ''}`, margin, y);
    y += 6;
  });

  pdf.save(`${type}-timetable-summary.pdf`);
}